//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freught1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FedEx_IMPORT_EXPORT_ZONE
    {
        public string COUNTRY_NAME { get; set; }
        public string E_IP { get; set; }
        public string E_IPF { get; set; }
        public string E_IE { get; set; }
        public string E_IEF { get; set; }
        public string I_IE { get; set; }
        public string I_IPF { get; set; }
        public string I_IEF { get; set; }
        public string I_IP { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
