//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freught1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ftestEntities : DbContext
    {
        public ftestEntities()
            : base("name=ftestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MS_CARRIER> MS_CARRIER { get; set; }
        public virtual DbSet<MS_CARRIER_PACKAGE_TYPE> MS_CARRIER_PACKAGE_TYPE { get; set; }
        public virtual DbSet<MS_CONFIGURATION> MS_CONFIGURATION { get; set; }
        public virtual DbSet<MS_EXCEL_WEIGHT_RATE> MS_EXCEL_WEIGHT_RATE { get; set; }
        public virtual DbSet<MS_GROUP_ACCESS> MS_GROUP_ACCESS { get; set; }
        public virtual DbSet<MS_SERVICE_TYPE> MS_SERVICE_TYPE { get; set; }
        public virtual DbSet<MS_USER> MS_USER { get; set; }
        public virtual DbSet<REF_COUNTRY> REF_COUNTRY { get; set; }
        public virtual DbSet<REF_EMAIL_LIST> REF_EMAIL_LIST { get; set; }
        public virtual DbSet<REF_GROUP_USER> REF_GROUP_USER { get; set; }
        public virtual DbSet<REF_MATRIX> REF_MATRIX { get; set; }
        public virtual DbSet<REF_MODULE> REF_MODULE { get; set; }
        public virtual DbSet<REF_PACKAGE_TYPE> REF_PACKAGE_TYPE { get; set; }
        public virtual DbSet<REF_STATUS_TYPE> REF_STATUS_TYPE { get; set; }
        public virtual DbSet<REF_SURCHARGE> REF_SURCHARGE { get; set; }
        public virtual DbSet<TR_UPLOAD_HISTORY> TR_UPLOAD_HISTORY { get; set; }
        public virtual DbSet<DHL_IMPORT_EXPORT_ZONE> DHL_IMPORT_EXPORT_ZONE { get; set; }
        public virtual DbSet<DHL_THIRD_ZONE> DHL_THIRD_ZONE { get; set; }
        public virtual DbSet<FedEx_IMPORT_EXPORT_ZONE> FedEx_IMPORT_EXPORT_ZONE { get; set; }
        public virtual DbSet<FedEx_THIRD_ZONE> FedEx_THIRD_ZONE { get; set; }
        public virtual DbSet<REF_WEIGHT_RATE1> REF_WEIGHT_RATE1 { get; set; }
    }
}
