//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freught1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_CARRIER
    {
        public string CARRIER_ID { get; set; }
        public string CARRIER_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string EXCEL_FILE { get; set; }
        public string IMPORT_SHEET_ZONE { get; set; }
        public string EXPORT_SHEET_ZONE { get; set; }
        public string THIRD_PARTY_SHEET_ZONE { get; set; }
        public string MATRIX_SHEET { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public string COUNTRY_HEADER_COL { get; set; }
    }
}
