//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freught1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_USER
    {
        public string USER_EMAIL { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string USER_STATUS { get; set; }
        public string TOKEN_VALUE { get; set; }
        public string GROUP_ID { get; set; }
        public string SITE_ID { get; set; }
        public string MOBILE { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<bool> IS_FORGOT_PASSWORD { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
