//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freught1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_WEIGHT_RATE_1
    {
        public double MIN { get; set; }
        public Nullable<double> MAX { get; set; }
        public Nullable<double> ZONE_1 { get; set; }
        public Nullable<double> ZONE_2 { get; set; }
        public Nullable<double> ZONE_3 { get; set; }
        public Nullable<double> ZONE_4 { get; set; }
        public Nullable<double> ZONE_5 { get; set; }
        public Nullable<double> ZONE_6 { get; set; }
        public Nullable<double> ZONE_7 { get; set; }
        public Nullable<double> ZONE_8 { get; set; }
        public Nullable<double> ZONE_9 { get; set; }
        public Nullable<double> ZONE_10 { get; set; }
        public Nullable<double> ZONE_11 { get; set; }
        public Nullable<double> ZONE_12 { get; set; }
        public Nullable<double> ZONE_13 { get; set; }
        public Nullable<double> ZONE_14 { get; set; }
        public Nullable<double> ZONE_15 { get; set; }
        public Nullable<double> ZONE_16 { get; set; }
        public Nullable<double> ZONE_17 { get; set; }
        public Nullable<double> ZONE_18 { get; set; }
        public Nullable<double> ZONE_19 { get; set; }
        public Nullable<double> ZONE_20 { get; set; }
        public Nullable<double> ZONE_21 { get; set; }
        public Nullable<double> ZONE_22 { get; set; }
        public Nullable<double> ZONE_23 { get; set; }
        public string CARRIER_ID { get; set; }
        public string DELIVER_TYPE { get; set; }
        public string SERVICE_ID { get; set; }
        public string PACKAGE_ID { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
