//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freught1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_MODULE
    {
        public string MODULE_ID { get; set; }
        public string MODULE_NAME { get; set; }
        public string PARENT_MODULE_ID { get; set; }
        public Nullable<int> MODULE_ORDER { get; set; }
        public string ICON_IMAGE { get; set; }
        public string URL { get; set; }
        public string MODULE_TYPE { get; set; }
        public Nullable<bool> IS_ENABLED { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
