//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freught1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_EMAIL_LIST
    {
        public string EMAIL_TITLE { get; set; }
        public string EMAIL_SUBJECT { get; set; }
        public string FILE_NAME { get; set; }
        public string EMAIL_TO { get; set; }
        public string EMAIL_CC { get; set; }
        public string EMAIL_BCC { get; set; }
        public string EMAIL_BODY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
