//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freught1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_UPLOAD_HISTORY
    {
        public string CARRIER_ID { get; set; }
        public System.DateTime UPLOAD_DATE { get; set; }
        public string EXCEL_FILE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
